# Generated by Django 4.1.3 on 2022-12-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_remove_orderproductview_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderProductView',
        ),
    ]
