# Generated by Django 4.1.3 on 2022-11-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_payment_orderproduct_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Order Accepted', 'Order Accepted'), ('Delivered Successfully', 'Delivered Successfully'), ('Order Cancelled', 'Order Cancelled')], default='Pending', max_length=50),
        ),
    ]
